### ISSUE TITLE
Partially broken output with a dll

### ISSUE THREAD

**Issue by theChaosCoder** [brechtsanders/pedeps#3] opened 2019-06-11 09:51 UTC
https://github.com/nekopanda/AviSynthPlus/releases/download/r2822/AvisynthNeo-r2822.zip

I called `listpedeps.exe 'D:\AviSynth.dll'` and it seems that the output is somewhat broken. I also see some strings of my PATH variable... and windows even makes a sound at the end.

Both, x86 & x64 avisynth.dll have this problem. It just looks different.

> ...
> api-ms-win-crt-time-l1-1-0.dll: _time64
> (null):  ê┐
> (null):  ê┐
> (null):  ê┐
> (null): path;c:\program files (x86)\common files½¶Ie
> (null): etup\bin;c:\program files\microsoft vs c░¶rb
> (null):  files\nodejs\;c:\program files\microsofë¶kl
> (null): rtableapps\xampp7.2\php;c:\programdata\c¢¶s
> (null): ýïM3Ê¾-ñÕ-ìAfn└[└ïE¾^Þmicrosofë¶kl
> EXPORTS
> AviSynth.dll: CreateScriptEnvironment @ 3
> AviSynth.dll: DllCanUnloadNow @ 4
> ...

**Comment by brechtsanders** [comment] 2019-06-11 16:12
I can't reproduce your problem.
In fact AviSynth.dll doesn't have dependancies outside the Windows folder, so no dependancies should be copied.
Which version did you use? Make sure to use the latest version (currently 0.1.5).

**Comment by theChaosCoder** [comment] 2019-06-11 16:47
I used the latest 0.1.5 x64 in powershell. Windows 10 (1903)
EDIT: Happens also in CMD shell.
EDIT 2:  listpedeps.exe x86 output looks a bit nicer, at least no strings from PATH are shown xD

listpedeps 64bit version:
![list2](https://user-images.githubusercontent.com/3579830/59291911-2c628c00-8c7c-11e9-9dc6-282e63571f03.gif)

**Comment by brechtsanders** [comment] 2019-06-30 19:54
Fixed in version 0.1.6

**Closed as completed by brechtsanders** 2019-06-30 19:54 UTC
